### ISSUE TITLE
Docker Images for Golang

### ISSUE THREAD

**Issue by shiroyasha** [semaphoreci/docker-images#11]
I need the following versions:

- 1.12
- 1.11
- 1.10
- 1.9
- 1.8
- 1.7
- 1.6

**Comment by bogyo210** [comment]
@shiroyasha cc @CommanderK5 
1.6, 1.7, 1.8  have issues build time : 
Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file), and build failes because of the official images, and debian jessie having issues.
1.9 , 1.10, 1.11, 1.12 build ok.
Q: 1.9-1.12 are enough for now or should i modify the build process to include a [fix](https://superuser.com/questions/1423486/issue-with-fetching-http-deb-debian-org-debian-dists-jessie-updates-inrelease)  ??

**Comment by shiroyasha** [comment]
1.9 , 1.10, 1.11, 1.12 are ok for now.

1.8, 1.7, 1.6 would be nice but we can do them later. They are pretty old in any case.

**Comment by shiroyasha** [comment]
Implemented here https://github.com/semaphoreci/dockerfile-renderer/pull/4.
